
#ifndef MPX_SPRING2018_ABOVE_C_LEVEL_PROCESSCOMMAND_H
#define MPX_SPRING2018_ABOVE_C_LEVEL_PROCESSCOMMAND_H

void help (int numword, char* args[]);

#endif //MPX_SPRING2018_ABOVE_C_LEVEL_PROCESSCOMMAND_H
